// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnhT4QdHRl9N8LPfmvbfXrp7052S4-N4U',
    appId: '1:658484160062:web:d53a0d2788e25dbbe8136f',
    messagingSenderId: '658484160062',
    projectId: 'e-commerse-app-50767',
    authDomain: 'e-commerse-app-50767.firebaseapp.com',
    databaseURL: 'https://e-commerse-app-50767-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerse-app-50767.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFZ_9zL9n2wRTtLPY9CkWRBl-5jSm4a8o',
    appId: '1:658484160062:android:f7ce9e661909b69ee8136f',
    messagingSenderId: '658484160062',
    projectId: 'e-commerse-app-50767',
    databaseURL: 'https://e-commerse-app-50767-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerse-app-50767.firebasestorage.app',
  );
}
